# Generated by Django 4.0.3 on 2022-05-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0011_tablehistory_waitlisthistory_table_party_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wait',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
